dist: bionic
services:
  - docker
install: skip

git:
  submodules: false

before_install:
  - openssl aes-256-cbc -K $encrypted_2b880785f91d_key -iv $encrypted_2b880785f91d_iv -in der-nackte-halloumi-base-travis.enc -out ~/.ssh/der-nackte-halloumi-base-travis -d

deploy:
  provider: script
  script:
    - bash scripts/deploy.sh
  on:
    branch: master
