version: "3.7"

services:
  api:
    image: dernacktehalloumi/api
    restart: always
    env_file: .env
    depends_on:
      - caddy
    networks:
      - app-network
  caddy:
    image: dernacktehalloumi/caddy
    restart: always
    env_file: .env
    volumes:
      - ./caddy_certs:/root/.caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
