version: "3.7"

services:
  api:
    build:
      context: ./api
    depends_on:
      - caddy
      - db

  caddy:
    build:
      context: ./caddy
      args:
        build_env: development

  db:
    image: postgres:12
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
    networks:
      - app-network

  migrations:
    build:
      context: ./api/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME?sslmode=disable",
        "-verbose",
        "up",
      ]
    depends_on:
      - db
