version: "3.7"

services:
  api:
    image: dernacktehalloumi/api:$API_IMAGE_TAG
    restart: always
    env_file: .env
    depends_on:
      - caddy
      - migrations
    networks:
      - app-network
  caddy:
    image: dernacktehalloumi/caddy:$CADDY_IMAGE_TAG
    restart: always
    env_file: .env
    volumes:
      - ./caddy_certs:/root/.caddy
    ports:
      - "80"
      - "443"
    networks:
      - app-network
  migrations:
    image: dernacktehalloumi/migrations:$MIGRATIONS_IMAGE_TAG
    container_name: migrations
    restart: on-failure
    env_file: .env
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME",
        "-verbose",
        "up",
      ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
